# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import scmddzcf_pb2 as scmddzcf__pb2


class DataStub(object):
  # missing associated documentation comment in .proto file


  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TextDzcf = channel.unary_unary(
        '/Dzcf.Data/TextDzcf',
        request_serializer=scmddzcf__pb2.ImagePath.SerializeToString,
        response_deserializer=scmddzcf__pb2.Jsondata.FromString,
        )


class DataServicer(object):
  # missing associated documentation comment in .proto file

  def TextDzcf(self, request, context):
    # missing associated documentation comment in .proto file
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TextDzcf': grpc.unary_unary_rpc_method_handler(
          servicer.TextDzcf,
          request_deserializer=scmddzcf__pb2.ImagePath.FromString,
          response_serializer=scmddzcf__pb2.Jsondata.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Dzcf.Data', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
